CREATE TABLE t_p2841448_elite_concierge_land.users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'member',
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  phone VARCHAR(50),
  city VARCHAR(100),
  country VARCHAR(100),
  birth_date DATE,
  bio TEXT,
  avatar_url TEXT,
  tier VARCHAR(20) DEFAULT 'silver',
  girl_level VARCHAR(20) DEFAULT 'newcomer',
  status VARCHAR(20) DEFAULT 'active',
  is_verified BOOLEAN DEFAULT false,
  invite_code_used VARCHAR(50),
  invited_by INTEGER,
  manager_id INTEGER,
  preferences JSONB DEFAULT '{}',
  languages TEXT[] DEFAULT '{}',
  interests TEXT[] DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  last_seen TIMESTAMP DEFAULT NOW()
);